defaults:
    - _self_

n_speakers: 4
fs: 16000
t_eps: 0.03
t_rev_init: 0.03
ema_decay: 0.999
valid_max_sep_batches: 1
time_sampling_strategy: uniform
train_source_order: power
init_hack: false
mmnr_thresh_pit: -10.0  # threshold for using pit with train_source_order=pit

score_model:
    _target_: models.score_models_dss.ScoreModelNCSNpp
    num_sources: ${model.n_speakers}
    stft_args:
        n_fft: 510
        hop_length: 128
        center: True
        pad_mode: "constant"
    backbone_args:
        _target_: models.ncsnpp.NCSNpp
        nf: 64
    transform: exponent
    spec_abs_exponent: 0.5
    spec_factor: 0.33
    spec_trans_learnable: false

loss:
    _target_: torch.nn.MSELoss

main_val_loss: val/si_sdr
main_val_loss_mode: max
val_losses:
    val/si_sdr:
        _target_: models.losses.SISDRLoss
        zero_mean: true
        clamp_db: 30
        reduction: mean
        sign_flip: true

optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.0
scheduler: null
grad_clipper:
    _target_: utils.FixedClipper
    max_norm: 5.0