_target_: pytorch_lightning.Trainer
accumulate_grad_batches: 1
min_epochs: 1
max_epochs: 10000
deterministic: true
accelerator: gpu
devices: -1
strategy: ddp
auto_select_gpus: true
check_val_every_n_epoch: 100
default_root_dir: .
profiler: false
