train:
    dl_opts:
        num_workers: 4
        shuffle: true
        batch_size: 4
    dataset:
        _target_: datasets.musdb_mix
        path: ${path.datasets.musdb_mix}
        fs: ${model.fs}
        cut: max
        split: train
        max_len_s: 1
        max_n_samples: null
valid:
    dl_opts:
        num_workers: 4
        shuffle: false
        batch_size: 4
    dataset:
        _target_: datasets.musdb_mix
        path: ${path.datasets.musdb_mix}
        fs: ${model.fs}
        cut: max
        split: valid
        max_len_s: 1
        max_n_samples: null
test:
    dl_opts:
        num_workers: 4
        shuffle: false
        batch_size: 4
    dataset:
        _target_: datasets.musdb_mix
        path: ${path.datasets.musdb_mix}
        fs: ${model.fs}
        cut: max
        split: test
        max_len_s: 1
        max_n_samples: null