defaults:
    - _self_
    - datamodule: default
    - model: default
    - trainer: default
    - experiment: null

seed: 64736289
name: default  # experiment name
train: true
test: false
# load_pretrained: exp/musdb18_16000/mixsde_score_fn/checkpoints/epoch-5799_si_sdr-0.000.ckpt

path:
    exp_root: exp
    datasets:
        wsj0_mix: data/wsj0_mix
        valentini: data/VCTK_DEMAND
        musdb_mix: data/musdb18
        musdb_mix_16000: data/musdb18_16000
    figures: figures
    
hydra:
    run:
        dir: ${path.exp_root}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
    job:
        config:
            override_dirname:
                kv_sep: '-'
                item_sep: '_'
                exclude_keys: 
                    - path.exp_root
