defaults:
    - _self_
    - datamodule: default
    - model: default
    - trainer: default
    - experiment: null

seed: 64736289
name: default  # experiment name
train: true
test: false
load_pretrained: /home/qor6271/Desktop/diff-music-sep/exp/musdb18_16000/2023-12-13_22-48-23_experiment-music-separation-16000-ouvekh_model.sde.sigma_max-0.5_model.sde.sigma_min-0.01_model.sde.theta_int_max-3.0_model.sde.theta_min-0.1_model.sde.theta_rho-4/checkpoints/epoch-5999_si_sdr-0.000.ckpt

path:
    exp_root: exp
    datasets:
        wsj0_mix: data/wsj0_mix
        valentini: data/VCTK_DEMAND
        musdb_mix: data/musdb18
        musdb_mix_16000: data/musdb18_16000
    figures: figures
    
hydra:
    run:
        dir: ${path.exp_root}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${hydra.job.override_dirname}
    job:
        config:
            override_dirname:
                kv_sep: '-'
                item_sep: '_'
                exclude_keys: 
                    - path.exp_root
